version: '3.5'
services:
  discovery:
    image: arivukb/discoveryservices:${BUILD_NUMBER}
    container_name: discovery-service
    ports:
      - "8761:8761"

  gateway:
    image: arivukb/gatewayservices:${BUILD_NUMBER}
    container_name: service-gateway
    ports:
      - "8765:8765"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    links:
      - discovery

  zipkin-service:
    image: arivukb/zipkinservices:${BUILD_NUMBER}
    container_name: zipkin-service
    ports:
      - "9411:9411"

  account-service:
    image: arivukb/accountservices:${BUILD_NUMBER}
    container_name: account-service
    ports:
      - "2222:2222"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    links:
      - discovery

  customer-service:
    image: arivukb/customerservices:${BUILD_NUMBER}
    container_name: customer-service
    ports:
      - "3333:3333"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    links:
      - discovery
